version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: pwd && ls 
  Push-Artifacts:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - store_artifacts:
           path: /root/project
           destination: sample-artifact
      - run: pwd && ls
      - run: find .
      - run: exit 1

workflows:
    build-and-publish:
      jobs:
        - build-and-test
        - Push-Artifacts
