version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: pwd && ls
  Push-Artifacts:
    steps:
      - run: ls && find .
      - store_artifacts:
           path: /home/project/*
           destination: sample-artifact

workflows:
    build-and-publish:
      jobs:
        - build-and-test
        - Push-Artifacts