version: 2.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: pwd && ls 
  Push-Artifacts:
    executor:
      name: node/default
    steps:
      - checkout
      - store_artifacts:
           path: /home/circleci/project
           destination: sample-artifact

workflows:
    build-and-publish:
      jobs:
        - build-and-test
        - Push-Artifacts
